title: BoletoP2P
url: /
baseurl:
google_analytics_key:

logo: /siteicon.png
description: Levando o bitcoin às pessoas “desbancarizadas”!
author: 
  name: Wallison Alves
  email: contato@boletop2p.com
  twitter: boletop2p
social:
  name: BoletoP2P
  links:
    - https://github.com/boletop2p/boletop2p.github.io

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

buying_embed: '<script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe src="https://donorbox.org/embed/give-sheep-the-vote?hide_donation_meter=true" height="685px" width="100%" style="max-width:425px; min-width:310px" seamless="seamless" id="dbox-form-embed" name="donorbox" frameborder="0" scrolling="no"></iframe>'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

_options:
  header_background_image:
    width: 1880
    height: 1880
