title: BoletoP2P
url: https://boletop2p.com
baseurl:
google_analytics_key:

logo: /siteicon.svg
description: Levando o bitcoin às pessoas “desbancarizadas”!
author: 
  name: Wallison Alves
  email: contato@boletop2p.com
  twitter: boletop2p
social:
  name: BoletoP2P
  links:
    - https://github.com/boletop2p/boletop2p.github.io

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 256
        height: 256

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 768
          height: 768
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

buying_embed: '<iframe frameborder="0" style="height:320px;width:50%;border:none;" src="https://forms.zohopublic.com/wado/form/obtervpn/formperma/JVxJ4b8wWUUayZo9daMY_NdxWlWtWCICjX-Hxk_lCbE"></iframe>'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

_options:
  header_background_image:
    width: 768
    height: 768
